---
title: "Reproducible Research: Peer Assessment 1"
author: "Mac McEacharn"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data

```{r echo=TRUE, warning=FALSE}
library(ggplot2)
library(lattice)

if (!file.exists("activity.csv") && file.exists("activity.zip")) {
    unzip("activity.zip", exdir = ".")
}
dataWithNA <- read.csv("activity.csv")
data <- na.omit(dataWithNA)
data$date <- as.Date(data$date, format = "%Y-%m-%d")
```


## What is mean total number of steps taken per day?
``` {r}
stepsDay <- tapply(data$steps, data$date, sum)

hist(stepsDay, breaks=20, main="Total Steps per Day",     
     xlab="Total Steps Per Day", 
     ylab="Frequency)")

```

```{r echo=TRUE, warning=FALSE}
meanStepsDay <- mean(stepsDay,na.rm=TRUE)
paste("Mean Steps per Day=",meanStepsDay)

```

```{r echo=TRUE, warning=FALSE}
medianStepsDay <- median(stepsDay,na.rm = TRUE)
paste("Median Steps per Day=",medianStepsDay)

```


## What is the average daily activity pattern?
```{r echo=TRUE, warning=FALSE}
stepsInterval <- aggregate(data$steps, 
                           by = list(interval = data$interval), 
                           FUN = mean, 
                           na.rm = TRUE)

colnames(stepsInterval) <- c("interval", "steps")
ggplot(stepsInterval, 
       aes(x= interval, y = steps)) +   
    geom_line(size = 1, color="gray") +   
    labs(x = "Interval", 
         y = "Steps", 
         title = "Average Daily Activity Pattern")

```

```{r echo=TRUE, warning=FALSE}
maxInterval <- stepsInterval[which.max(stepsInterval$steps),]
paste("The interval having the most steps is interval ",
      maxInterval[1],
      sep="")
```
## Imputing missing values

```{r echo=TRUE, warning=FALSE}
sumNASteps <- sum(is.na(dataWithNA$steps))
sumNADate <- sum(is.na(dataWithNA$date))
sumNAInterval <- sum(is.na(dataWithNA$interval))

totNA <- sumNASteps+ sumNADate + sumNAInterval

paste("The number of missing values is ",
      totNA,
      sep="")
```

### Filling in missing data
```{r echo=TRUE, warning=FALSE}

filledInData <- dataWithNA

filledInData$steps[is.na(filledInData$steps)] <- 
    median(dataWithNA$steps, 
               na.rm=TRUE)

filledInData <- aggregate(steps ~ date, 
                          data=filledInData, 
                          sum, 
                          na.rm=TRUE)

hist(filledInData$steps, 
     breaks=20, 
     main="Total Steps per Day",     
     xlab="Total Steps Per Day",
     ylab="Frequency")
```     

```{r echo=TRUE, warning=FALSE}
meanStepsDayFilledIn <- mean(filledInData$steps,na.rm=TRUE)
paste("Adjusted Mean Steps per Day=",meanStepsDayFilledIn)


```

```{r echo=TRUE, warning=FALSE}
medianStepsDayFilledIn <- median(filledInData$steps,na.rm = TRUE)
paste("Adjusted Median Steps per Day=",medianStepsDayFilledIn)
```

*The impact of imputing missing data on the estimates of the total daily number of steps is shown below:*

```{r echo=TRUE, warning=FALSE}
paste("The Difference Between Measured Mean Steps per Day and Adjusted Mean Steps Per Day is =",meanStepsDay - meanStepsDayFilledIn)

paste("The Difference Between Measured Median Steps per Day and Adjusted Median Steps Per Day is =",medianStepsDay - medianStepsDayFilledIn)

```

## Are there differences in activity patterns between weekdays and weekends?
